services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb_image
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u${MYSQL_USER} -p${MYSQL_PASSWORD} --silent"]
      interval: 10s
      timeout: 3s
      retries: 5

  wordpress:
    build: ./requirements/wordpress
    image: wordpress_image
    container_name: wordpress
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    environment:
      - DB_HOST=mariadb
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9000"]
      interval: 10s
      timeout: 3s
      retries: 5

  nginx:
    build: ./requirements/nginx
    image: nginx_image
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/strodrig/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/strodrig/data/wordpress

networks:
  inception:
    driver: bridge


